# Generated by Django 3.2 on 2021-04-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyMentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('twitter_link', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube_link', models.CharField(blank=True, max_length=200, null=True)),
                ('text_body', models.TextField(blank=True, max_length=1500, null=True)),
            ],
        ),
    ]
