# Generated by Django 3.2 on 2021-04-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyMentors',
            new_name='MyMentor',
        ),
    ]
