# Generated by Django 3.2 on 2021-04-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_yourletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourletter',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='static/images'),
        ),
    ]
