# Generated by Django 3.2 on 2021-04-16 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0005_alter_yourletter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourletter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yourletter',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='yourletter',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='yourletter',
            name='text',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
