# Generated by Django 3.2 on 2021-04-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0006_auto_20210416_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yourletter',
            options={'ordering': ['-created']},
        ),
    ]
