# Generated by Django 3.2 on 2021-04-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0009_auto_20210421_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourletter',
            name='image',
            field=models.ImageField(default='dennis_olQ5Tn1.jpeg', max_length=255, upload_to=''),
        ),
    ]
