# Generated by Django 3.2 on 2021-04-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0010_alter_yourletter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourletter',
            name='image',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
